### ISSUE TITLE
Verify need for v3yangle, vparity in L3 pipeline

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romancal#1167]
The exposure level pipeline doesn't presently use the v3yangle or vparity keywords, though it may need to in the future when setting the telescope pointing.  The mosaicing pipeline does use these keywords, however, and it's not obvious to me that it needs to; the WCS object contains all the information that should be needed.  We should investigate whether these keywords are actually required.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/RCAL-834?focusedCommentId=699431#comment-699431):_

The sole place where the wcsinfo is used is in [stcal.alignment.util._generate_tranform](https://github.com/spacetelescope/stcal/blob/fa14c81aea3403c6d6191b992176483e455ca2c9/src/stcal/alignment/util.py#L71)

This routine creates an `astropy.Model` of scale/rotation for the output wcs. 

A couple of approaches can be taken:

Modification of stcal: `_generate_tranform` could be modified to calculate such values from the existing refmodel wcs. This could cause issues with jwst compatibility.

romancal-specific: The transform can be pre-calculated in romancal's make_output_wcs. Passing the transform in through the `wcs_from_footprints` call, would avoid the need for _generate_tranform to use the wcsinfo block. The advantage here is that this is a romancal-specific change only, making use of existing api.

Unless otherwise dictate, [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) will take the romancal-specific path.

**Comment by schlafly** [comment]
Could you check whether JWST actually uses this?  I think our goal is for eventually Webb++ to start using stcal.alignment, but currently I think Roman is the only user.  i.e., I think that if we think the _generate_transform API isn't right, we have flexibility to change it.

**Comment by nden** [comment]
These are used to determine the roll angle `roll_ref` , computed in set_telescope_pointing.

**Comment by schlafly** [comment]
Sorry, I haven't tracked the full path, but looking at this briefly, _generate_transform is ~recomputing the WCS object we already have, and accepts a transform argument that we could imagine supplying it to avoid that path?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/RCAL-834?focusedCommentId=699693#comment-699693):_

After discussions with [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) , this issue is being closed without further work modulo the following:
 - The default output WCS uses the roll, parity, and v3yangle from the first input WCS. This isn't great but absent direction (which will provided for the skycells) isn't horrible.
 - To make this insensitive to the wcsinfo, the WCS can be used directly to compute the angles, scales, and parities. But since this is only computing the choice of WCS there is no real bug here.
 - A better job computing the output shape can be implemented in the future if needed.
