### ISSUE TITLE
ELP returns input to tweakreg, rather than output from tweakreg?

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romancal#1283]
The ELP returns the "results" input to tweakreg, rather than the "result" output from tweakreg.
https://github.com/spacetelescope/romancal/blob/main/romancal/pipeline/exposure_pipeline.py#L185-L190
That's probably a bug?

**Comment by schlafly** [comment]
Relatedly, I'm missing where in the ELP the loop over the difference SCAs making up the association occurs.  Dave, could you look at this when you get a chance?

**Comment by mairanteodoro** [comment]
@schlafly Ultimately, I think we want to return `result`, instead of `results`. However, since the updates from `TweakRegStep` are made in-place, both objects will have the same processed content.

The main difference between both objects is that `result` is a list of `ImageModel`, whereas `results` is a `ModelLibrary`.

**Comment by schlafly** [comment]
Okay, let's close this one too.  The missing loop got fixed as part of your changes to the ELP.
