### ISSUE TITLE
Create pipeline documentation for readthedocs

### ISSUE THREAD

**Issue by dmggh** [spacetelescope/romancal#8]
This is for RCAL-18 : "Enable pipeline documentation build on readthedocs".

**Comment by dmggh** [comment]
Redundant.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-18](https://jira.stsci.edu/browse/RCAL-18)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-18](https://jira.stsci.edu/browse/RCAL-18)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-18](https://jira.stsci.edu/browse/RCAL-18)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-18](https://jira.stsci.edu/browse/RCAL-18)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-18](https://jira.stsci.edu/browse/RCAL-18)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-18](https://jira.stsci.edu/browse/RCAL-18)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-18?focusedCommentId=495228#comment-495228):_

The current build failure on readthedocs is caused by having stpipe documentation under docs:

 

<https://github.com/spacetelescope/romancal/tree/main/docs/roman>

 

Similar to code, we want to include only ROman specific parts in the documentation. Since stpipe is not part of romancal (and may not be in the future) docs/roman/stpipe needs to be removed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/RCAL-18?focusedCommentId=499102#comment-499102):_

Via GitHub PR #&#x2060;61, I wiped the readthedocs environment and did a rebuild, which appears to solve the problem. Now the built document contains my latest updates - all of the previous JWST references have been correctly replaced. Unless someone has any objections, I think this completes what is needed for RCAL-18. The built docs are at : <https://roman-cal-pipeline.readthedocs.io/en/latest/index.html>
